version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=sqlite:///movies.db
      - site=https://www.kinoafisha.info/rating/movies/
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movies
